import 'dart:async';
import '../models/gateway_config.dart';
import 'storage_service.dart';
import 'websocket_service.dart';

/// AuthService - Backend service for authentication
/// Responsible for: Device identity, token management, auth flow
class AuthService {
  static final AuthService _instance = AuthService._internal();
  factory AuthService() => _instance;
  AuthService._internal();

  final StorageService _storage = StorageService();
  final WebSocketService _wsService = WebSocketService();

  /// Check if authenticated with gateway
  Future<bool> isAuthenticated(String gatewayId) async {
    final token = await _storage.getDeviceTokenAsync(gatewayId);
    return token != null && token.isNotEmpty;
  }

  /// Check if device identity exists
  Future<bool> hasDeviceIdentity(String gatewayId) async {
    final identity = await _storage.getDeviceIdentityAsync(gatewayId);
    return identity != null;
  }

  /// Get or create device identity
  /// Note: Actual key generation handled by crypto utility
  Future<Map<String, dynamic>> getOrCreateIdentity(String gatewayId) async {
    var identity = await _storage.getDeviceIdentityAsync(gatewayId);
    
    if (identity == null) {
      // Identity should be generated by crypto utility
      // This is a placeholder - actual implementation generates Ed25519 keypair
      identity = {
        'deviceId': 'device_${DateTime.now().millisecondsSinceEpoch}',
        'publicKey': '',
        'privateKey': '',
      };
      await _storage.saveDeviceIdentity(gatewayId, identity);
    }
    
    return identity!;
  }

  /// Clear authentication data for re-authentication
  Future<void> clearAuth(String gatewayId) async {
    final config = _storage.getGatewayConfig(gatewayId);
    if (config != null) {
      await _storage.saveGatewayConfig(config.copyWith(deviceToken: null));
    }
    await _storage.deleteDeviceIdentity(gatewayId);
  }

  /// Validate gateway connection
  Future<bool> validateGatewayConnection(GatewayConfig config) async {
    try {
      await _wsService.connect(config);
      
      // Wait for connection result
      final connected = await _wsService.connectionStream
          .firstWhere((state) => 
            state == WsConnectionState.connected || 
            state == WsConnectionState.error,
          );
      
      if (connected == WsConnectionState.connected) {
        await _wsService.disconnect();
        return true;
      }
      
      return false;
    } catch (e) {
      print('Gateway validation failed: $e');
      return false;
    }
  }

  /// Refresh device token
  Future<void> refreshToken(String gatewayId) async {
    await _wsService.disconnect();
    final config = _storage.getGatewayConfig(gatewayId);
    if (config != null) {
      await _storage.saveGatewayConfig(config.copyWith(deviceToken: null));
      await _wsService.connect(config);
    }
  }

  /// Save device token after successful authentication
  Future<void> saveToken(String gatewayId, String token) async {
    await _storage.saveDeviceToken(gatewayId, token);
    
    final config = _storage.getGatewayConfig(gatewayId);
    if (config != null) {
      await _storage.saveGatewayConfig(config.copyWith(
        deviceToken: token,
        lastConnected: DateTime.now(),
      ));
    }
  }
}
